const STATUS_CODE_OK = 200;
const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const SERVER_ERROR_CODE = 500;
const NOT_IMPLEMENTED_ERROR_CODE = 501;
const EXCEPTION_STATUS_CODE = 502;

module.exports = {
    STATUS_CODE_OK,
    BAD_REQUEST_STATUS_CODE,
    NOT_FOUND_STATUS_CODE,
    SERVER_ERROR_CODE,
    NOT_IMPLEMENTED_ERROR_CODE,
    EXCEPTION_STATUS_CODE
}